// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firebase/firestore/proto/mutation.proto

package com.aves.flamingodb.proto;

public interface MutationQueueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:firestore.client.MutationQueue)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * An identifier for the highest numbered batch that has been acknowledged by
   * the server. All WriteBatches in this queue with batch_ids less than or
   * equal to this value are considered to have been acknowledged by the
   * server.
   * </pre>
   *
   * <code>int32 last_acknowledged_batch_id = 1;</code>
   * @return The lastAcknowledgedBatchId.
   */
  int getLastAcknowledgedBatchId();

  /**
   * <pre>
   * A stream token that was previously sent by the server.
   * See StreamingWriteRequest in datastore.proto for more details about usage.
   * After sending this token, earlier tokens may not be used anymore so only a
   * single stream token is retained.
   * </pre>
   *
   * <code>bytes last_stream_token = 2;</code>
   * @return The lastStreamToken.
   */
  com.google.protobuf.ByteString getLastStreamToken();
}
