// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firebase/firestore/proto/maybe_document.proto

package com.aves.flamingodb.proto;

public interface NoDocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:firestore.client.NoDocument)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The name of the document that does not exist, in the standard format:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * The name of the document that does not exist, in the standard format:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The time at which we observed that it does not exist.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp read_time = 2;</code>
   * @return Whether the readTime field is set.
   */
  boolean hasReadTime();
  /**
   * <pre>
   * The time at which we observed that it does not exist.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp read_time = 2;</code>
   * @return The readTime.
   */
  com.google.protobuf.Timestamp getReadTime();
}
