// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firebase/firestore/proto/maybe_document.proto

package com.aves.flamingodb.proto;

public interface UnknownDocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:firestore.client.UnknownDocument)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The name of the document that is known to exist, in the standard format:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * The name of the document that is known to exist, in the standard format:
   * `projects/{project_id}/databases/{database_id}/documents/{document_path}`
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The version at which we know the document exists.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp version = 2;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <pre>
   * The version at which we know the document exists.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp version = 2;</code>
   * @return The version.
   */
  com.google.protobuf.Timestamp getVersion();
}
